default_language_version:
  python: python3.9

repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.283
    hooks:
      - id: ruff

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: debug-statements
    - id: check-ast
    - id: check-json
    - id: check-toml
    - id: check-yaml
    - id: detect-private-key

  - repo: https://github.com/stratasan/hadolint-pre-commit
    rev: cdefcb096e520a6daa9552b1d4636f5f1e1729cd
    hooks:
    - id: hadolint
      files: docker/Dockerfile
